root: true

extends:
  - mysticatea
  - mysticatea/browser
  - plugin:prettier/recommended
rules:
  require-jsdoc: off
  mysticatea/arrow-parens: off

overrides:
  - files: ["*.js"]
    parserOptions:
      sourceType: script
      ecmaVersion: 2017
      ecmaFeatures:
        globalReturn: true
    plugins:
      - node
    globals:
      __dirname: false
      __filename: false
      clearImmediate: false
      exports: false
      module: false
      process: false
      require: false
      setImmediate: false
    rules:
      node/exports-style:
        - error
        - module.exports
      node/no-deprecated-api: error
      node/no-extraneous-require: error
      node/no-missing-require: error
      node/no-unpublished-bin: error
      node/no-unpublished-require: error
      node/no-unsupported-features: error
      node/process-exit-as-throw: error
      node/shebang: error
      prettier/prettier:
        - error
        - tabWidth: 4
          semi: false
          trailingComma: all

  - files: ["*.ts"]
    parser: typescript-eslint-parser
    parserOptions:
      sourceType: module
      ecmaVersion: 2017
    plugins:
      - import
      - node
    rules:
      func-style: off
      init-declarations: off
      lines-between-class-members: off
      no-invalid-this: off
      no-loop-func: off
      no-undef: off
      no-unused-vars: off
      no-use-before-define: off
      one-var: [error, never]
      valid-jsdoc: off
      import/default: error
      import/first: error
      import/named: error
      import/newline-after-import: error
      import/no-absolute-path: error
      node/no-extraneous-import: error
      node/no-missing-import: error
      node/no-unpublished-import: error
      prettier/prettier:
        - error
        - tabWidth: 4
          semi: false
          trailingComma: all
          parser: typescript
    settings:
      node:
        tryExtensions: [".ts", ".js"]

  - files: ["*.vue"]
    parser: vue-eslint-parser
    parserOptions:
      sourceType: module
      ecmaVersion: 2017
    plugins:
      - import
      - node
      - vue
    rules:
      import/default: error
      import/first: error
      import/named: error
      import/newline-after-import: error
      import/no-absolute-path: error
      node/no-extraneous-import: error
      node/no-missing-import: error
      node/no-unpublished-import: error
      vue/comment-directive: error
      vue/jsx-uses-vars: error
      vue/no-async-in-computed-properties: error
      vue/no-dupe-keys: error
      vue/no-duplicate-attributes: error
      vue/no-parsing-error: error
      vue/no-reserved-keys: error
      vue/no-shared-component-data: error
      vue/no-side-effects-in-computed-properties: error
      vue/no-template-key: error
      vue/no-textarea-mustache: error
      vue/no-unused-vars: error
      vue/require-component-is: error
      vue/require-render-return: error
      vue/require-v-for-key: error
      vue/require-valid-default-prop: error
      vue/return-in-computed-property: error
      vue/valid-template-root: error
      vue/valid-v-bind: error
      vue/valid-v-cloak: error
      vue/valid-v-else-if: error
      vue/valid-v-else: error
      vue/valid-v-for: error
      vue/valid-v-html: error
      vue/valid-v-if: error
      vue/valid-v-model: error
      vue/valid-v-on: error
      vue/valid-v-once: error
      vue/valid-v-pre: error
      vue/valid-v-show: error
      vue/valid-v-text: error
      vue/attribute-hyphenation: error
      vue/html-end-tags: error
      vue/html-indent: [error, 4]
      vue/html-self-closing: error
      vue/mustache-interpolation-spacing: error
      vue/name-property-casing: error
      vue/no-multi-spaces: error
      vue/require-default-prop: error
      vue/require-prop-types: error
      vue/v-bind-style: error
      vue/v-on-style: error
      vue/attributes-order: error
      vue/html-quotes: error
      vue/no-confusing-v-for-v-if: error
      vue/order-in-components: error
      vue/this-in-template: error
      vue/html-closing-bracket-newline: error
      vue/html-closing-bracket-spacing: error
      vue/prop-name-casing: error
      prettier/prettier:
        - error
        - tabWidth: 4
          semi: false
          trailingComma: all
    settings:
      node:
        tryExtensions: [".vue", ".ts", ".js"]
